name: seal
version: 0.1.0.0
github: bartoszluka/seal
description: A simple, C-like programming language
license: BSD3
author: Bartek Łuka
maintainer: bartoszluka1@gmail.com
copyright: MIT

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ImportQualifiedPost
  - ScopedTypeVariables
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
  - base >= 4.7 && < 5
  - relude
  - text
  - megaparsec
  - parser-combinators
  - string-interpolate
  - process

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  seal-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - seal

tests:
  seal-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - seal
      - filepath
      - directory
      - raw-strings-qq
      - HUnit
      - hspec
      - hspec-core
      - hspec-contrib
      - hspec-golden
      - hspec-megaparsec
      - tasty-silver
      # - hspec-smallcheck
      # - smallcheck
